Import('*')

Source('./RRAM/ai_chip.cpp')
Source('./RRAM/core.cpp')
Source('./RRAM/memhub.cpp')
Source('./RRAM/memory.cpp')
Source('vdev.cc')
SimObject('VirtualDevice.py')

DebugFlag('VirtualDevice')
